#!/bin/bash -
python3 -u train.py --method NT2 --dname cora --data_dir ./data/cora --raw_data_dir ./raw_data/cocitation/cora --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 6 --hidden 36 --n-layers 4 --dropout 0.73 --input_dropout 0.79
python3 -u train.py --method NT2 --dname citeseer --data_dir ./data/citeseer --raw_data_dir ./raw_data/cocitation/citeseer --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 5 --hidden 21 --n-layers 1 --dropout 0.76 --input_dropout 0.62 --with-edge-proxy
python3 -u train.py --method NT2 --dname coauthor_cora --data_dir ./data/coauthor_cora --raw_data_dir ./raw_data/coauthorship/cora --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 3 --hidden 35 --n-layers 2 --dropout 0.66 --input_dropout 0.75
python3 -u train.py --method NT2 --dname NTU2012 --data_dir ./data/NTU2012 --raw_data_dir ./raw_data/NTU2012 --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 7 --hidden 61 --n-layers 1 --dropout 0.80 --input_dropout 0.18
python3 -u train.py --method NT2 --dname house-committees-100 --data_dir ./data/house-committees-100 --raw_data_dir ./raw_data/house-committees --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 7 --hidden 37 --n-layers 8 --dropout 0.21 --input_dropout 0.45
python3 -u train.py --method NT2 --dname senate-committees-100 --data_dir ./data/senate-committees-100 --raw_data_dir ./raw_data/senate-committees --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 5 --hidden 58 --n-layers 10 --dropout 0.74 --input_dropout 0.51
python3 -u train.py --method NT2 --dname pubmed --data_dir ./data/pubmed --raw_data_dir ./raw_data/cocitation/pubmed --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 1 --hidden 9 --n-layers 2 --dropout 0.06 --input_dropout 0.26 --with-edge-proxy
python3 -u train.py --method NT2 --dname 20newsW100 --data_dir ./data/20newsW100 --raw_data_dir ./raw_data/20newsW100 --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 6 --hidden 8 --n-layers 3 --dropout 0.67 --input_dropout 0.32
python3 -u train.py --method NT2 --dname walmart-trips-100 --data_dir ./data/walmart-trips-100 --raw_data_dir ./raw_data/walmart-trips --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 6 --hidden 17 --n-layers 10 --dropout 0.31 --input_dropout 0.09 --with-edge-proxy
python3 -u train.py --method NT2 --dname congress-bills-100 --data_dir ./data/congress-bills-100 --raw_data_dir ./raw_data/congress-bills --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 6 --hidden 12 --n-layers 8 --dropout 0.61 --input_dropout 0.68 --with-edge-proxy
python3 -u train.py --method NT2 --dname coauthor_dblp --data_dir ./data/coauthor_dblp --raw_data_dir ./raw_data/coauthorship/dblp --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 1 --hidden 39 --n-layers 10 --dropout 0.78 --input_dropout 0.36
python3 -u train.py --method NT2 --dname yelp --data_dir ./data/yelp --raw_data_dir ./raw_data/yelp --runs 10 --epochs 500 --patience 500 --display_step 1 --heads 2 --hidden 10 --n-layers 4 --dropout 0.59 --input_dropout 0.30
python3 -u train.py --method NT2 --dname ModelNet40 --data_dir ./data/ModelNet40 --raw_data_dir ./raw_data/ModelNet40 --runs 10 --epochs 500 --display_step 1 --heads 6 --hidden 26 --n-layers 1 --dropout 0.72 --input_dropout 0.28 --with-edge-proxy
